baseURL = 'https://Entenschnitzel.github.io'
languageCode = 'de-de'
title = 'Webseiten mit gohugo Bauen'
theme = "w체ste"
defaultContentlanguage = "de"

[params]
body_classes = "avenir bg-white"
text_color = "black"
background_color_class = "bg-white"
showReadingTime = "false"
custom_css = ["custom.css"]

[languages]
 [languages.de]
    title = "Webseiten mit gohugo Bauen"
    subtitle = "Praktikums Projekt"
    keywords = ""
    copyright = ""
    menuMore = "Mehr Anzeigen"
    writtenBy = "von"
    readMore = "weiterlesen"
    readOtherPosts = "andere Eintr채ge"
    newerPosts = "neue Eintr채ge"
    olderPosts = "alte Eintr채ge"
    minuteReadingTime = "minuten gelesen"
    dateFormatSingle = "02.01.2006"
    dateFormatList = "02.01.2006"